-- Seed inserts for the universities table
-- Values are source-safe anchors only; details missing from official sources are preserved as Not Officially Available in the JSON seed.

INSERT INTO universities (name, short_name, official_website, admissions_portal, location, year_established, hec_recognition, accreditation, university_type, source_note) VALUES
('Sir Syed University of Engineering & Technology', 'SSUET', 'https://www.ssuet.edu.pk/', 'https://edusmartz.ssuet.edu.pk/AdmissionPortal/Signin', 'Karachi, Pakistan', 'Not Officially Available', 'Not Officially Available', 'Not Officially Available', 'Private', 'Official website and admissions portal'),
('Habib University', 'HU', 'https://habib.edu.pk/', 'https://eapplication.habib.edu.pk/', 'Block 18, Gulistan-e-Jauhar, Karachi, Sindh, Pakistan', 'Not Officially Available', 'Not Officially Available', 'Not Officially Available', 'Private', 'Official website and admissions portal'),
('Institute of Business Administration, Karachi', 'IBA Karachi', 'https://iba.edu.pk/', 'https://onlineadmission.iba.edu.pk/', 'Karachi, Pakistan', 'Not Officially Available', 'Not Officially Available', 'NBEAC ''W'' Category Accreditation', 'Public', 'Official website and admissions portal'),
('DHA Suffa University', 'DSU', 'https://www.dsu.edu.pk/', 'https://erp.dsu.edu.pk/web/signin/', 'Karachi, Pakistan', 'Not Officially Available', 'Not Officially Available', 'Not Officially Available', 'Private', 'Official website and admissions portal'),
('Iqra University', 'IU', 'https://iqra.edu.pk/', 'https://admissions.iqra.edu.pk/', 'Karachi, Hyderabad, Islamabad', 'Not Officially Available', 'Times Higher Education and UIGREENMETRIC rankings shown on official site', 'Not Officially Available', 'Private', 'Official website and admissions portal'),
('Mohammad Ali Jinnah University', 'MAJU', 'https://jinnah.edu/', 'https://admissions.jinnah.edu/', 'Main Shahrah-e-Faisal, Block-6, PECHS, Karachi', '1998', 'Chartered by Sindh government', 'W Category shown on official site', 'Private', 'Official website and admissions portal'),
('University of Karachi', 'UoK', 'https://uok.edu.pk/', 'https://uok.edu.pk/admissions/index.php', 'University Road, Karachi, Pakistan', '1951', 'Not Officially Available', 'Not Officially Available', 'Public', 'Official website and admissions portal'),
('NED University of Engineering & Technology', 'NEDUET', 'https://www.neduet.edu.pk/', 'https://ugadmissions.neduet.edu.pk/', 'Karachi, Pakistan', '1977', 'QEC ''W'' Category; HEC ranking score 95.33% on official site', 'ISO 9001:2015', 'Public', 'Official website and admissions portal'),
('Bahria University Karachi Campus', 'Bahria Karachi', 'https://www.bahria.edu.pk/', 'https://www.bahria.edu.pk/home/index#admissions_page', '13 National Stadium Road, Karachi', '2000', 'Federally chartered public sector university established by Pakistan Navy', 'Not Officially Available', 'Public', 'Official website and admissions portal'),
('Hamdard University', 'Hamdard', 'https://hamdard.edu.pk/', 'Not Officially Available', 'Not Officially Available', 'Not Officially Available', 'Not Officially Available', 'Not Officially Available', 'Private', 'Official website only; admissions content not extractable in this pass'),
('Ziauddin University', 'ZU', 'https://zu.edu.pk/', 'https://admission.zu.edu.pk/', 'Karachi, Pakistan', 'Not Officially Available', 'HEC-recognised degree-awarding institute', 'Not Officially Available', 'Private', 'Official website and admissions portal'),
('Indus University', 'Indus University', 'https://indus.edu.pk/', 'http://inquiry.induscms.com:81/ords/r/erasoft/a200/login', 'Gulshan-e-Iqbal and North Karachi, Karachi', 'Not Officially Available', 'Not Officially Available', 'Not Officially Available', 'Private', 'Official website and inquiry portal'),
('SZABIST University', 'SZABIST', 'https://szabist.edu.pk/', 'http://admissions.szabist.edu.pk/', 'Karachi, Pakistan', 'Not Officially Available', 'NATIONAL & INTERNATIONAL AFFILIATIONS/ACCREDITATIONS page exists', 'Not Officially Available', 'Private', 'Official website and admissions portal'),
('Institute of Business Management', 'IoBM', 'https://iobm.edu.pk/', 'Not Officially Available', 'Korangi Creek, Karachi-75190', 'Not Officially Available', 'Not Officially Available', 'Not Officially Available', 'Private', 'Official website only; admissions portal not surfaced'),
('Dawood University of Engineering & Technology', 'DUET', 'https://duet.edu.pk/', 'http://admissions.duet.edu.pk/', 'Karachi, Pakistan', '2013', 'Elevated to university status in 2013 from Dawood College', 'Not Officially Available', 'Public', 'Official website and admissions portal'),
('FAST-NUCES Karachi Campus', 'FAST Karachi', 'https://nu.edu.pk/', 'https://admissions.nu.edu.pk/OLAR/Login', 'St-4 Sector 17-D on National Highway, Karachi; 22-G Block-6 PECHS, Karachi', '2000', 'Federally chartered university established in July 2000', 'Not Officially Available', 'Private', 'Official website and admissions portal'),
('COMSATS University', 'COMSATS', 'https://comsats.edu.pk/', 'https://admissions.comsats.edu.pk/', 'Islamabad principal seat with multiple campuses across Pakistan', '2000', 'Multi-campus public sector university', 'Nature Index and QS references on official site', 'Public', 'Official website and admissions portal'),
('Pakistan Institute of Engineering and Applied Sciences', 'PIEAS', 'https://www.pieas.edu.pk/', 'http://admissions.pieas.edu.pk/', 'Lehtrar Road, Islamabad, Pakistan', 'Not Officially Available', 'Ranked No. 1 for Engineering & Technology by HEC (official site text)', 'Not Officially Available', 'Public', 'Official website and admissions portal');
